### ISSUE TITLE
Finish provider re-organization

### ISSUE THREAD

**Issue by bithavoc** [heapsource/mongoose-attachments#15]
In order to reflect recent changes, We need to:
- Update the readme to reflect the re-organization of the providers
- Remove the providers code
- Remove knox and aws2js dependencies of package.json
- Add new contributos to Readme.md
- Version bump to 0.1.0(in a separate Pull Request)

**Comment by nuarhu** [comment]
Hi @thepumpkin1979 

isn't that what Joe's 2nd commit updates (at least a good part of it)?
https://github.com/joewright/mongoose-attachments/commit/65b4ba6698f0686b5e0f4e241bf94e31b12ccc8f
from #11 (2nd commit further down).

**Comment by bithavoc** [comment]
I didn't see that, Yeah, you can merge that. The localfs module was uploaded to NPM, please test it to see if it's working property.

**Comment by nuarhu** [comment]
Should I change the package.json to version 0.1.0 _before_ merging this major change?

**Comment by bithavoc** [comment]
Merge and then comes the Version Bump :)

I'm not saying that we have right now(my bad), but the Workflow should be:
1. Open a change in Readme.md to reflect that the version in Master is unestable and have a link to the tag in github of the last version published to NPM.
2. Open a change in Changelog.md(we don't have one right now xD) to reflect the next version number and label it with "Next Release". The next version should be predictable, if the last published version was v0.1.0, the next version should v0.1.1 or if this is non-backward compatible release, it should be v1.0.0 or v2.0.0. The git tag of the last available/published version should be added as a link to Changelog.
3. Commit and Merge pull Requests in Master branch and updating Changelog.md to include the issue id that were solved of related in this upcoming release.
4. Once we determinate that we are not receiving more pull requests or don't have any plans to make more changes, we close Changelog removing "Next Release" from the current version.
5. Make a version bump
6. Publish to NPM
7. Rinse and Repeat.

Notes:
- An example of a beautiful changelog: https://github.com/intridea/grape/blob/master/CHANGELOG.markdown
- A beautiful readme: https://github.com/intridea/grape/blob/master/README.markdown , pay special attention to the "Stable Release" section and "Contributing to Grape".

What do you think of this?

**Comment by nuarhu** [comment]
Please have a look - and merge if it's ok.

**Comment by bithavoc** [comment]
what else do we need? are the other modules ready to be published?

**Comment by nuarhu** [comment]
Yes, I would say so.

What about #11 - it includes the necessary changes to the README and removes the provider files. Can't we simply merge that? (You just closed it without merging?)

Concerning https://github.com/firebaseco/mongoose-attachments-localfs/pull/4 - I would rather not merge that one. It's supposed to be "local fs", at least for now, and this issue is about problems when copying images from one device to another.

**Comment by nuarhu** [comment]
Ok, after checking the package.json files of the provider modules:
- localfs still requires mongoose-attachments 0.0.x - this should now be 0.1.x. Unfortunately, this version is already tagged with 0.1.0 (localfs) - do we have to bump the version, again? Well, actually it should work with 0.0.x, as well. But it would be better to reference the next minor version.
  Also, package.json names this "mongoose-attachments-fs" but the documentation states "mongoose-attachments-localfs". I don't remember exactly what we agreed on? If it's "localfs" we could have another module "netfs" with all the code required for cross device handling as already reported in https://github.com/firebaseco/mongoose-attachments-localfs/issues/4 . Either way, it has to be corrected to be the same all over the project.
- knox has version 1.0.0 and references mongoose-attachments 0.0.x. The latter should be 0.1.x. Is the former ok?
- aws2js same as knox.

mongoose-attachments-knox and mongoose-attachments-aws2js are not on npm, yet.

**Comment by nuarhu** [comment]
... and the provider name should be "localfs" or "fs" depending on whether the module is mongoose-attachments-localfs or mongoose-attachments-fs. (Currently, it's "fs".)

Wich one do you prefer? It's messed up as it is, anyway: npm knows about "mongoose-attachments-fs" but the github module is "mongoose-attachments-localfs"? Sorry :-(

**Comment by bithavoc** [comment]
I can republish with -force and reset the tag, no problem.

Choose whatever name you'd like and let me know what I need to change.

Don't worry, If we need to re-publish then we do it.

**Comment by bithavoc** [comment]
I think local-fs is ok since the repo name is already local-fs, I don't know, we can still rename it I guess

**Comment by bithavoc** [comment]
In the readme, let's include links to the other providers.

**Comment by bithavoc** [comment]
btw, the readme still says `Supports Amazon S3 out-of-the-box.` hehe, that's no longer true.

**Comment by nuarhu** [comment]
Ok, I will change localfs to be localfs everywhere in mongoose-attachments-localfs and make a pull request for that.

For the decision on how to require the providers - whether they return the attachments instance right away, I'd rather have a different branch. (See my comment in #17 )

The package.json of mongoose-attachments still says 0.0.4 but I didn't want to just change that as part of some commit.

**Comment by bithavoc** [comment]
How are we with this reorganizacion @nuarhu ?

**Comment by nuarhu** [comment]
The pull request #17 removes the providers and updates the README. I didn't want to merge it without you having a look at it. Can you check and merge?

There is still to decide whether the provider submodules should return a reference to mongoose-attachments. (See the comment in the pull request.) Depending on that, there is a little work to be done in the submodules.

**Comment by nuarhu** [comment]
Hi @thepumpkin1979 ,

sorry for not working on this for so long. I hope to have some spare time this week to finish this, and maybe have a look at the issues that are coming in.

**Comment by nuarhu** [comment]
Ready for release from my part.
