### ISSUE TITLE
Removing files?

### ISSUE THREAD

**Issue by droganov** [heapsource/mongoose-attachments#18]
Hello.
How to remove files? I call doc.remove() it's popped out of mongo, but images are still on the s3...

How's gonna clear that stuff? Can't find the subject in the docs...

Thank you,
Serge

**Comment by Routhinator** [comment]
No answer for this yet?

**Comment by nuarhu** [comment]
For now, you have to implement the deletion by yourself.

Feel free to contribute a pull request. :+1:
