### ISSUE TITLE
Requiring provider module should return a reference to mongoose-attachments

### ISSUE THREAD

**Issue by nuarhu** [heapsource/mongoose-attachments#24]
Currently, to use mongoose-attachments you need to require the provider as well as the core module. The Readme is not completely clear about this. It says that mongoose-attachments comes bundled with each provider but the examples still show the old way. (Or maybe I'm just reading it wrong?)

Anyway, I think it would be a good thing to allow:

```
var attachments = require('mongoose-attachments-localfs');
```

(for all providers)

The steps for this are:
- Change all providers to return a reference to mongoose-attachments instead of a reference to the provider class. I think that latter is not needed in clients, anyway? Or would there be a problem in changing that?
- Change the Readmes of all providers accordingly.
- Change the Readme of the core module accordingly.

This is a requirement for #15 .

**Comment by nuarhu** [comment]
I think these have been the last changes for 0.1.0? Sorry again for the delay.

**Comment by Bajix** [comment]
I painfully noticed this issue as well. Do you have any proper examples with how it should be used currently, or do you think there will be a patch soon?

**Comment by nuarhu** [comment]
I'm waiting for thepumpkin1979 to approve the pull request.

For now, you will have to require the mongoose-attachments module explicitly:

```
// unused var, but you need to require it before using mongoose-attachements
var provider = require('mongoose-attachments-aws2js');
// this is the var you use as mongoose plugin as described in the Readme
var attachments = require('mongoose-attachments');
```

**Comment by bithavoc** [comment]
Hi @nuarhu,

What's needs to be changed to get this working? This pull request seems to be out of date. https://github.com/heapsource/mongoose-attachments/pull/25

I'd like to publish a new version 0.1.1 by wednesday.

How can I help you solve this issue?

**Comment by nuarhu** [comment]
Why do you think #25 is out of date? Doesn't it describe how we want it to work?

I _think_ the code base should be ready for 0.1.1. But, of course, I could be overlooking something. (Just came back from vacation... :-D )

**Comment by nuarhu** [comment]
@thepumpkin1979 are you still waiting for some action from me?
I am no longer a collaborator (since you moved the repo to heapsource) so I cannot tell whether the outstanding merges can still be done automatically.
Wouldn't it be nice to get on with the release? :-)

**Comment by bithavoc** [comment]
Hey @nuarhu 

Sorry about the team confusion, you are now again a collaborator.

let me know when you want me to publish the new version

**Comment by nuarhu** [comment]
Thanks! I've merged all my outstanding pull requests. So, I'm all set for the release. :+1:
