### ISSUE TITLE
TypeError: Object { _id: 5219f3858ec1ba1c28000001 } has no method 'attach'

### ISSUE THREAD

**Issue by henrynok** [heapsource/mongoose-attachments#31]
Hi I am new to mongoose-attachments. When I try the example I get a TypeError: Object { _id: 5219f3858ec1ba1c28000001 } has no method 'attach' .

I have tried everything please advise if I am doing anything wrong. I use the latest versions of Mongoosejs, Node and Express.

I tried to use it with all providers but no luck.

**Comment by nuarhu** [comment]
Could you please post the code where you are initalizing and attaching mongoose-attachments?

Please make sure that you use the documentation of the stable version https://github.com/heapsource/mongoose-attachments/tree/v0.0.4 .

**Comment by vinh0604** [comment]
Hi, I face the same problem today. Here is my model config:

``` javascript
AttachmentSchema.plugin(attachments, {
  directory: '/app/uploads/startups/logos',
  storage : {
    providerName: 'localfs'
  },
  properties: {
    image: {
      styles: {
        original: {
          // keep the original file
        },
        thumb: {
          thumbnail: '100x100^',
          gravity: 'center',
          extent: '100x100',
          '$format': 'jpg'
        },
        detail: {
          resize: '400x400>',
          '$format': 'jpg'
        }
      }
    }
  }
});

module.exports = mongoose.model('Attachment', AttachmentSchema);
```

And in controller:

``` javascript
    var attachment = new Attachment();

    attachment.attach('image', req.files.file, function (err) {
      if (err) {
        return next(err);
      }

      attachment.save(function (err, attachment) {
        if (err) {
          res.status = 422;
          res.json({success: false});
        }

        res.json({success: true, attachment: attachment});
      });
    });
```

**Comment by vinh0604** [comment]
After debugging, I realized that the `mongoose-attachments-localfs` does not return the referrence for `mongoose-attachments` as mentioned in the doc. 

I solved the problem by directly require the `mongoose-attachments` and call the plugin() method via it.

**Comment by henrynok** [comment]
Hi vinh0604,

Could you please paste the code for your solution?

**Comment by nuarhu** [comment]
Thanks for your comment. It made me realize that the tag 0.1.0 is too old. The master version (untagged) of `mongoose-attachments-localfs` correctly exports a reference to attachments. Sorry for that. The documentation was ahead of the code for some time.

**Comment by henrynok** [comment]
Will you be tagging a new version to correct the problem or should we use the master version?

**Comment by nuarhu** [comment]
As a workaround:

```
require('mongoose-attachments-localfs');
var attachments = require('mongoose-attachments');
```

should work.

**Comment by nuarhu** [comment]
@henrynok 
The next release is actually planned. It is done by @thepumpkin1979 .
Until then either use master or the workaround + tag 0.1.0.

**Comment by nuarhu** [comment]
Fixed in current master of `mongoose-attachments-localfs` (not yet in tag 0.1.0).

**Comment by rngadam** [comment]
I think it would be really important to release this fix as I just spent 2 hours tracking down this problem. Sure, part of it was because I'm new to MongooseJS and wasn't sure if I was doing something wrong but still...

Or perhaps at least a README note? 

The workaround wasn't working for me, but changing my package.json to:

```
"mongoose-attachments-localfs": "git+ssh://git@github.com:heapsource/mongoose-attachments-localfs.git#master",
```

...did fix it.
