### ISSUE TITLE
Getting a uniform directory structure in a large app??

### ISSUE THREAD

**Issue by Routhinator** [heapsource/mongoose-attachments#33]
I've been trying to work out how get a proper directory structure using this app. What I want is this:

3 main image types: 
- userImage: Users profile image
- userBackground: Users background image for profile.
- postImage: images that are attached to posts.

userImage and userBackground will be attached to the user model, while the postImages will be attached to the individual post documents.

I'd like to end up with the following structure so deleting a user and all of their content from the S3 is as easy as possible:

Example based on userImage:

user.ObjectID/model.Name/imageName/imageStyleName.extension

5224a679aeac8a241e000001/user/userImage/small.jpg
5224a679aeac8a241e000001/user/userImage/medium.jpg
5224a679aeac8a241e000001/user/userImage/large.jpg

Example based on postImage

user.ObjectID/user/post/post.ObjectID/imageID-style.extension

5224a679aeac8a241e000001/posts/5224a679aeac8a241e000001/5224a679aeac8a241e000001-large.jpg

When I delete the user, this way I can just tell it to delete the users folder and all of their files are gone from S3.

For the life of me I can't seem to achieve it. I can't get the id of the user being saved from 'this.id' or figure out a way to add any parameters to the filename aside from <property>-style.extention

How would I accomplish this?

**Comment by nuarhu** [comment]
Have you tried using the `directory` option as in the example from the Readme?

``` javascript
PostSchema.plugin(attachments, {
  directory: 'achievements',
  storage: {
    providerName: 'aws2js',
    options: {
      key: '<key>',
      secret: '<secret>',
      bucket: '<bucket>'
    }
  },
  properties: {
     // ...
  }
});

var Post = mongoose.model('Post', PostSchema);
```

Otherwise you would have to extend the storage provider you are using and create a custom `createOrReplace()` implementation for it.

**Comment by Routhinator** [comment]
I've been trying the directory structure but it only seems to take a static variable. When I try to pass the ID of the model being saved to it, I get undefined. 

```
UserSchema.plugin(attachments, {
    directory: this.id + '/profile/' + propertyName + '-' + styleName + ext,
    filenameId: '_id',
    storage: config.s3,
    properties: {
        userImage: {
            styles: {
                original: {
                    // keep the original file
                },
                small: {
                    resize: '60x60',
                    '$format': 'jpg'
                },
                medium: {
                    resize: '140x140',
                    '$format': 'jpg'
                },
                large: {
                    resize: '300x300',
                    '$format': 'jpg'
                }
            }
        }
        userBackground: {
            styles: {
                original: {
                    // keep the original file
                },
                large: {
                    resize: '1600x1200',
                    '$format': 'jpg'
                }
            }
        }
    }
});
```

The above code is an example of what I would like to achieve. 'this.id' comes out undefined.. and the other three variables are taken from inside the mongoose-attachments code itself to show you exactly what I'd like to acieve using the variables the ap uses.

**Comment by nuarhu** [comment]
Yes, it has to be static. You cannot even use a function. To achieve this you will have to override `createOrReplace` of the storage provider you are using and build the directory structure in a different way.

The other possibility is that you modify mongoose-attachments to accept a function for the `directory` option that is evaluated when an image is stored - and provide a pull request for it. :+1:

**Comment by Routhinator** [comment]
I feel this is an important issue, and I will certainly need the feature in my app and future apps, I will add the necessary code and submit a pull request.

**Comment by nuarhu** [comment]
That's great! Thanks a lot!
