### ISSUE TITLE
Issue with undefined 'filenameId'

### ISSUE THREAD

**Issue by Routhinator** [heapsource/mongoose-attachments#34]
If filenameId is not defined in the settings now, all files are saved as 'undefined-style.extension' - selfModel.id does not seem to be defined.

For now it can be worked around by always setting "fileNameID": "_id"

**Comment by nuarhu** [comment]
mongoose-attachments uses Mongoose's `id` property: http://mongoosejs.com/docs/guide.html#id

You have not by any chance passed `id: false` as option to your schema?

**Comment by Routhinator** [comment]
Nope, and the id propety is being passed correctly, I was logging the object because I was trying to determine how it was coming out undefined, however it was defined every time with a valid ObjectID

**Comment by Routhinator** [comment]
Actually I just realized what it is. When mongoose creates an ID - it's _id and not id - I think the mongoose-attachment code that is the issue on line 170:

```
          var filenameId = options.filenameId ? selfModel[options.filenameId] : selfModel.id;
```

It only checks selfModel.id and not selfModel._id

**Comment by nuarhu** [comment]
Please see the link I've posted before:

> Mongoose assigns each of your schemas an id virtual getter by default which returns the documents _id

**Comment by Routhinator** [comment]
Yes, well. It isn't working. I've verified this multiple times.

**Comment by nuarhu** [comment]
Do your Mongoose model classes return an `id` if you call that directly (e.g. in a console output)?

If so, please post the code where you setup the schema and attach mongoose-attachments. Also post the versions you are using (the entries in your package.json for Mongoose and mongoose-attachments).

**Comment by Routhinator** [comment]
My Mongoose models only return _id - I've tried multiple times to get it to be a more standard id but even though it's defined as id in the schema, Mongoose only ever returns _id when a model is rendered.

This is my user model source in it's entirety:

module.exports = function (config) {
    /**
     \* Module dependencies.
     */
    var mongoose = require('mongoose')
        , provider = require('mongoose-attachments-aws2js')
        , attachments = require('mongoose-attachments')
        , Schema = mongoose.Schema
        , ObjectId = Schema.ObjectId
        , bcrypt = require('bcrypt')
        , restify = require('restify')
        , SALT_WORK_FACTOR = 10;

```
/**
 * User Schema
 */
var UserSchema = new Schema({
    id: ObjectId,
    firstName: { type: String, trim: true },
    lastName: { type: String, trim: true },
    email: { type: String, trim: true, unique:true },
    bio: { type: String, trim: true },
    newEmail: { type: String, trim: true, default: '' },
    emailValidatedFlag: { type: Boolean, default: false },
    username: { type: String, trim: true },
    role: { type: String, enum: ['Joe', 'Subscriber', 'Admin'], default: 'Joe' },
    gender: { type: String, enum: ['Male', 'Female'], default: 'Male' },
    password: { type: String, trim: true },
    tempPasswordFlag: { type: Boolean, default: false }
});

/**
 * Virtuals
 */
UserSchema
    .virtual('fullName')
    .get(function () {
        return this.firstName + ' ' + this.lastName;
    });

UserSchema
    .virtual('userlower')
    .get(function () {
        return this.username.toLowerCase();
    });

UserSchema
    .virtual('emaillower')
    .get(function () {
        return this.email.toLowerCase();
    });
```

// Bcrypt middleware
    UserSchema.pre('save', function(next) {
        var user = this;

```
    if(!user.isModified('password')) return next();

    if (!user.validatePresenceOf(user.username)) {
        next(new restify.MissingParameterError('USERMISSING'));
    }
    if (!user.validatePresenceOf(user.firstName)) {
        next(new restify.MissingParameterError('FNAMEMISSING'));
    }
    if (!user.validatePresenceOf(user.lastName)) {
        next(new restify.MissingParameterError('LNAMEMISSING'));
    }
    if (!user.validatePresenceOf(user.role)) {
        next(new restify.MissingParameterError('ROLEMISSING'));
    }
    if (!user.validatePresenceOf(user.email)) {
        next(new restify.MissingParameterError('EMAILMISSING'));
    }
    if (user.email.indexOf('@') <= 0) {
        next(new restify.MissingParameterError('EMAILINVALID'));
    }

    if (!user.isNew) {
        if (!user.validatePresenceOf(user.password)) {
            next(new restify.MissingParameterError('PASSMISSING'));
        }
    }

    if ((user.password) && (user.password.length < 7)) {
        next(new restify.MissingParameterError('SHORTPASS'));
    }

    bcrypt.genSalt(SALT_WORK_FACTOR, function(err, salt) {
        if(err) return next('Cannot generate salt. Error:'+err);

        bcrypt.hash(user.password, salt, function(err, hash) {
            if(err) return next('Cannot hash password. Error:'+err);
            user.password = hash;
            next();
        });
    });
});

UserSchema.plugin(attachments, {
    directory: 'users',
    filenameId: '_id',
    storage: config.s3,
    properties: {
        userImage: {
            styles: {
                original: {
                    // keep the original file
                },
                small: {
                    resize: '60x60',
                    '$format': 'jpg'
                },
                medium: {
                    resize: '140x140',
                    '$format': 'jpg'
                },
                large: {
                    resize: '300x300',
                    '$format': 'jpg'
                }
            }
        }
    }
});

UserSchema.methods.validatePresenceOf = function (value) {
    return value && value.length
};
```

// Password verification
    UserSchema.methods.comparePassword = function(candidatePassword, cb) {
        bcrypt.compare(candidatePassword, this.password, function(err, isMatch) {
            if(err) return cb(err);
            cb(null, isMatch);
        });
    };

```
return mongoose.model('User', UserSchema, 'users');
```

};

**Comment by Routhinator** [comment]
Module versions:

Mongoose-attachments - "version": "0.1.0",
Mongoose - "version": "3.6.18",

In my package.json I'm calling 'latest' for mongoose, and I'm directly calling the repo for mongoose-attachments as the npm version seemed behind.

**Comment by nuarhu** [comment]
Do you really need to define `id: ObjectId`? I don't set the `id` at all in my schemas but let Mongoose handle that. I introduced custom names for custom ids if it ever was necessary.

If you are overriding `id` you will have to use the work around you described at the beginning. mongoose-attachments can only fall back to Mongoose's `id` if you are not interfering with it, of course.

**Comment by Routhinator** [comment]
That was just what all the demos had shown me, I figured if I didn't define the ID it wouldn't be returned from the DB (coming from a mySQL background) - I wasn't aware it could be left undefined. I cetainly wasn't aware that would override anything. Also.. if I am overriding.. and I'm defining 'id' - why do all my models come back with '_id' despite that definition?

**Comment by nuarhu** [comment]
Because `_id` and `id` are offered by Mongoose by default if you don't turn them off.

http://mongoosejs.com/docs/guide.html#id

**Comment by Routhinator** [comment]
Well, I'm reinitializing the DB and removing the filenameID specification and the id definition to retest. If everything works as expected than that was it.

**Comment by Routhinator** [comment]
That was it. Problem solved.
