### ISSUE TITLE
Documentation Seems Wrong

### ISSUE THREAD

**Issue by tastycode** [heapsource/mongoose-attachments#40]
This line `var attachments = require('mongoose-attachments-aws2js');` in the readme indicates that you can pass this directly to `TargetSchema.plugin(attachments)`. 

In practice, this didn't work. I inspected `attachments` and got this.

``` javascript
function S3Storage(options) {
  attachments.StorageProvider.call(this, options);
  s3.setCredentials( options.key, options.secret );
  s3.setBucket( options.bucket );
  this.acl = options.acl || false;
  this.client = s3;
  this.endpoint = options.endpoint || ( 'https://' + options.bucket + '.s3.amazonaws.com' );
}
```

Whereas when i used `var attachments = require('mongoose-attachments'), attachments_s3 = require('mongoose-attachments-aws2js');` I got this when I inspected `attachments`

``` javascript
function (schema, options) {
  options = options || {};
  if(typeof(options.directory) !== 'string') throw new Error('option "directory" is required');
  if(typeof(options.properties) !== 'object') throw new Error('option "properties" is required');
  if(typeof(options.storage) !== 'object') throw new Error('option "storage" is required');
  var storageOptions = options.storage;
  storageOptions.schema = schema;

  if(typeof(storageOptions.providerName) !== 'string') throw new Error('option "storage.providerName" is required');
  var providerPrototype = findProvider(storageOptions.providerName)
//truncated for brevity
```

You get the point, the actual plugin code that patches the schema seem to only be exposed when requiring the core plugin, requiring the storage provider `mongoose-attachments-aws2js` only exports the storage provider itself? 

Not sure if this is an issue on my end, or an issue with the docs but I thought I would bring it to your attention.

**Comment by nuarhu** [comment]
Please see the section "Stable Release" at the beginning of the Readme:

> You're reading the documentation for the next release of Mongoose-Attachments, which should be 0.1.0. The current stable release is 0.0.4.
