### ISSUE TITLE
Support for all image/* mime types

### ISSUE THREAD

**Issue by nuarhu** [heapsource/mongoose-attachments#6]
Hi,

my application checks for mime type image/\* and allows everything that comes along. Now, a BMP fails as it is not by default in the list of supportedDecodingFormats (line 30 of attachements.js).

It came as a bit of a surprise that there is such a list of supported formats, in the first place. Might be a bit naive of me (?) but I would have thrown everything at ImageMagick which could be handled by its "identify" method. This just seems like an unnecessary restriction at this point.

With this white list I'm quite stuck. Can we agree on a possibility to make it optional? Something like "if the list is not empty: use it - otherwise do not use it"? Maybe make it even the default not to use it?

I could create a pull request for that solution. Or is there some other, better way?

**Comment by bithavoc** [comment]
Hi @nuarhu,

the library not only uses `identify`, it also uses `convert`as weel. if you use convert in something that is not an image then things go wrong.

Disable the restriction locally and you will see, it's right here: https://github.com/firebaseco/mongoose-attachments/blob/master/lib/attachments.js#L111

`var canTransform = !!atts;`

I accept pull requests, just make sure we keep legacy behavior and your changes can be configured only in specific cases.

Let me know how it goes.

**Comment by bithavoc** [comment]
Since you are accepting all kind of files, seems like you don't want to perform transforms for some files. You can use a style with no transformations to keep the original file.

See here: https://github.com/firebaseco/mongoose-attachments#keeping-the-original-file

**Comment by nuarhu** [comment]
Hi,

thanks for the quick answer. I'm restricting to files that have a mime-type starting with "image/". I would suppose that these are all images?

To build the list of supported input formats, the output of "convert -list format" filtered for entries with "r" (read support) could be used as default?

What do you think?

**Comment by bithavoc** [comment]
That sounds cool, I could accept a pull request for that.
Thanks @nuarhu

**Comment by nuarhu** [comment]
Just for the records: this is the pull request https://github.com/firebaseco/mongoose-attachments/pull/7

**Comment by nuarhu** [comment]
Closed with https://github.com/firebaseco/mongoose-attachments/pull/7
