### ISSUE TITLE
Attach image as Update

### ISSUE THREAD

**Issue by sharathprabhal** [heapsource/mongoose-attachments#8]
I could not find any doc on how specify the image when updating a document. 

I could not use findById to get the document and then call "attach" as the method is not on the document, it is available only on the model itself.

**Comment by sharathprabhal** [comment]
I was wrong about using findById and doing an explicit save, that works!

**Comment by mongoh** [comment]
Hi, I am having the same issue here... I cannot call attach on a Query type.

How was this solved prior?

Thanks,

**Comment by mongoh** [comment]
Nevermind, solved it. Seems to be an issue with 1.0? 0.0.4 works fine.
